### ISSUE TITLE
[BUG] - Lockdown mode fails in additional profiles

### ISSUE THREAD

**Issue by ZingyAwesome** [zaneschepke/wgtunnel#962]
**Describe the bug**
Lockdown mode fails to connect when running WG tunnel in multiple profiles. The first profile can connect just fine but then subsequent profiles fail to connect: the endpoints are resolved but never complete a handshake.

Errors I saw from the log that are probably of importance (from private space profile):
`UAPIOpen: mkdir /data/data/com.zaneschepke.wireguardautotunnel: permission denied`
`SOCKS5 net.Listen failed: listen tcp 127.0.0.1:25344: bind: address already in use`
`Routine failed: listen tcp 127.0.0.1:25344: bind: address already in use`

**Smartphone (please complete the following information):**

- Device: Pixel 9
- Android Version: 16
- App Version: 4.0.0
- App mode: Lockdown

**To Reproduce**

1. Go to main profile
2. Enable lockdown mode and enable a tunnel
3. Go to another profile, in my case private space
4. Enable lockdown mode there, enable a tunnel
5. The second tunnel will never complete a handshake.

**Expected behavior**
The second profile should work like the first and handshake normally. This problem isn't present using the normal VPN mode. I also believe prior to 4.0.0 using the in-app killswitch with multiple profiles worked fine.

**Screenshots (Only if necessary)**

**Additional context**
None.

**Comment by zaneschepke** [comment]
Ah! I forgot about this possibility. 

Yes, lockdown mode behind the scenes uses a SOCKS5 proxy to route the traffic from the dummy tunnel to the virtual tunnel. If you're running in multiple profiles then these bind ports would already be taken by the other profile. 

I need to change this so that we use a random open port instead. I'll look into fixing this. Thanks for the report.

**Comment by ZingyAwesome** [comment]
Also another possibly related issue to lockdown mode - whenever it's enabled, some apps get the wrong network status. Syncthing-Fork believes the WiFi is metered even if set to unmetered in settings. SeedVault (the backup solution included in GrapheneOS and CalyxOS) believes that mobile data is in use even if mobile data is disabled (I think this is the same issue but SeedVault reports it in a weird way). 
Either way lockdown mode seems to break some syncing apps which have settings like 'disable on metered connections' or 'disable on mobile data'. No idea why, I didn't have this issue with the previous killswitch implementation.

**Comment by zaneschepke** [comment]
> Also another possibly related issue to lockdown mode - whenever it's enabled, some apps get the wrong network status. Syncthing-Fork believes the WiFi is metered even if set to unmetered in settings. SeedVault (the backup solution included in GrapheneOS and CalyxOS) believes that mobile data is in use even if mobile data is disabled (I think this is the same issue but SeedVault reports it in a weird way). Either way lockdown mode seems to break some syncing apps which have settings like 'disable on metered connections' or 'disable on mobile data'. No idea why, I didn't have this issue with the previous killswitch implementation.

I'm pretty sure Android, by default, considers any VPN connection to be a metered connection and so other apps that observe if you are on a metered network will always trigger that the current network is metered when you are connected to a VPN. 

Although, it seems there is a way I can override this default behavior. I can look into that.

--edit

From some brief research, it seems different VPN apps handle this differently. Some default to metered, others default to unmetered.

Probably the best solution is to provide users a toggle per tunnel so they can set this themselves whether they want that tunnel to be considered metered or not.

I've created a new issue for this metered setting feature #966

**Comment by zaneschepke** [comment]
I've added metered options to be configured for the kill switch and at a tunnel level for regular vpn mode. 

I've also fixed this bug so that we select a random open port lockdown mode to prevent this multiple profile conflict. This should all be fixed in the latest nightly.

**Comment by ZingyAwesome** [comment]
I'm afraid to say that I don't think the issue is fully resolved. I managed to get lockdown mode to connect once in private space a few days ago but after locking and reopening the private space I am back in the same situation where the endpoints are resolved but the handshake never completes with 0B sent and received.
After looking at the log there are no more `address already in use` errors which is an improvement, but `UAPIOpen: mkdir /data/data/com.zaneschepke.wireguardautotunnel: permission denied` still persists which is the only error I can see.

**Comment by zaneschepke** [comment]
> I'm afraid to say that I don't think the issue is fully resolved. I managed to get lockdown mode to connect once in private space a few days ago but after locking and reopening the private space I am back in the same situation where the endpoints are resolved but the handshake never completes with 0B sent and received. After looking at the log there are no more `address already in use` errors which is an improvement, but `UAPIOpen: mkdir /data/data/com.zaneschepke.wireguardautotunnel: permission denied` still persists which is the only error I can see.

Ah! I see. Thanks for pointing this out. Yeah, the port issue is fixed. 

We likely need to make this UAPI file location unique as well. I'll work on fixing this.

**Comment by ZingyAwesome** [comment]
I still can't get this to work in private space. The endpoints resolve but the handshake never completes and the stats stay on 0B sent, 0B received. There are no errors in the log unlike before.
